#!/bin/bash

CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"

# Skip the image build and use a host mounted volume to get up to date code
FAST=${FAST:-0}

cd "$(dirname "$0")" || exit

if [[ $FAST -eq 0 ]]; then
  $CONTAINER_RUNTIME build -t acapy-redis-queue-test -f ../Dockerfile.test ../.. || exit 1
fi

DOCKER_ARGS=""

if [[ $FAST -eq 1 ]]; then
  DOCKER_ARGS="${DOCKER_ARGS} -v $(pwd)/../redis_queue:/usr/src/app/redis_queue:z"
fi

# on Windows, docker run needs to be prefixed by winpty
if [ "$OSTYPE" == "msys" ]; then
  CONTAINER_RUNTIME="winpty docker"
fi

$CONTAINER_RUNTIME run --rm -ti --name acapy-redis-queue-test-runner \
	$DOCKER_ARGS acapy-redis-queue-test "$@"
